language: python
  - "3.6"

sudo: required
dist: xenial

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov

before_script:
  - python mitasny/generate_secret.py > mitasny/secret_key.py
  - python manage.py makemigrations
  - python manage.py makemigrations tasks
  - python manage.py migrate
  - python manage.py migrate tasks

script:
  - coverage run --source='./tasks' manage.py test tasks -v2
  - coverage report

after_success:
  - codecov
